### ISSUE TITLE
Pollen sensor unavailable causes AttributeError: 'NoneType' object has no attribute 'lstrip'

### ISSUE THREAD

**Issue by codyc1515** [ciejer/metservice-weather#11]
## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.33.0
Stage | running
Available Repositories | 1346
Downloaded Repositories | 21
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 116.5 GB
disk_used | 17.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.11.4), Tailscale (0.13.1), File editor (5.7.0), Scrypted (18-jammy-full.s6-v0.68.0), Node-RED (16.0.2), Terminal & SSH (9.8.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 22, 2023 at 15:44
-- | --
current_recorder_run | November 25, 2023 at 04:44
estimated_db_size | 246.77 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.13
-- | --
can_reach_server | ok
can_reach_spec | pending
logged_accounts | 1
total_devices | 5

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Sometimes the MetService website unpublishes the pollen information. When this happens, the sensor is unavailable (fine) but it generates an exception in the logs because it is not handled correctly.

### Reproduction steps

MetService website does not have pollen counts right now.

Issue is here https://github.com/ciejer/metservice-weather/blob/30ce42cd589d51fd3f552fc03c5cd033b3bb84d2/custom_components/metservice_weather/weather_current_conditions_sensors.py#L159

### Debug logs

```text
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/metservice_weather/weather_current_conditions_sensors.py:159
Integration: MetService New Zealand Weather (documentation, issues)
First occurred: 05:05:21 (16 occurrences)
Last logged: 10:05:54

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/config/custom_components/metservice_weather/sensor.py", line 119, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 501, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/sensor.py", line 106, in native_value
    return self.entity_description.value_fn(self._sensor_data, self._unit_system)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather_current_conditions_sensors.py", line 159, in <lambda>
    str, ". ".join(i.capitalize() for i in data.lstrip(" ")[0:254].split(". "))
                                           ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lstrip'
```

**Comment by codyc1515** [comment]
Still occuring.

**Comment by codyc1515** [comment]
We need to add a check if the mapping exists here:

https://github.com/ciejer/metservice-weather/blob/f86f74e0c311c7d95e002a24b603e906159d4577/custom_components/metservice_weather/weather_current_conditions_sensors.py#L154C1-L154C1
