### ISSUE TITLE
Migrate from desktop to mobile API to avoid entities becoming unavailable

### ISSUE THREAD

**Issue by codyc1515** [ciejer/metservice-weather#12]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

You will experience issues with the layout of the desktop page changing and shifting, particularly as the layout and content appears to be more or less dictated by MetService's advertisers.

### Describe the solution you'd like

Use the mobile app API. It is static and does not change at advertisers whims so it should be significantly more stable. This will also avoid the need to strip and format some of the raw data. Because the URL is based on the geolocation (which I think can be auto-obtained in HA) you also avoid the need to set a static location and maintain a mapping list of locations. Fixes #11.

```
GET /mobile/nz/weatherData/-43.XXX/172.XXX HTTP/1.1
Host: api.metservice.com
apiKey: l7xx2a4b9096debf47acb352d84a6ef39461
Accept: */*
User-Agent: MetServiceNZ/2.19.3 (com.metservice.iphoneapp; build:332; iOS 17.1.1) Alamofire/5.4.3
Accept-Language: en-CA;q=1.0
Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8
Connection: keep-alive
```

**Comment by ciejer** [comment]
Hi @codyc1515 - had a brief look at this.
The current approach uses the public api, rather than an API setup - I see there's an API key in your above example, how can this be gained?
Thanks, and great to meet a local!
-Chris

**Comment by codyc1515** [comment]
It's simply the iOS API key. The issue you face with the "public" API is that the layout shifts often which will break this integration necessitating updates and restarts to HA every time that occurs.

**Comment by ciejer** [comment]
@codyc1515 I've pushed branch mobile_api as a first cut - wrapping up for today, but is working for basic sensors.
Codebase is an absolute shambles (more than my usual).
I intend to have a look at the daily/hourly forecasts before shipping this as 0.3, with code cleanup as 0.3.1.

**Comment by codyc1515** [comment]
Broken now on the mainline plug-in due to a MetService change.

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor (documentation, issues)
First occurred: 04:08:17 (1 occurrences)
Last logged: 04:08:17

Error while setting up metservice_weather platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/metservice_weather/sensor.py", line 48, in async_setup_entry
    sensors = [
              ^
  File "/config/custom_components/metservice_weather/sensor.py", line 49, in <listcomp>
    WeatherSensor(coordinator, description) for description in SENSOR_DESCRIPTIONS
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/sensor.py", line 82, in __init__
    self._sensor_data = _get_sensor_data(
                        ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/sensor.py", line 136, in _get_sensor_data
    result = get_from_dict(sensors[RESULTS_CURRENT], keys)
                           ~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

```
Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:509
Integration: Weather (documentation, issues)
First occurred: 04:08:17 (1 occurrences)
Last logged: 04:08:17

Error adding entities for domain weather with platform metservice_weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 754, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 973, in state
    return self.condition
           ^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 112, in condition
    if self.coordinator.get_current(FIELD_CONDITIONS) in CONDITION_MAP:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/coordinator.py", line 156, in get_current
    result = self.get_from_dict(self.data[RESULTS_CURRENT], keys)
                                ~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

```
Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:369
Integration: Weather (documentation, issues)
First occurred: 04:08:17 (1 occurrences)
Last logged: 04:08:17

Error while setting up metservice_weather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 754, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 973, in state
    return self.condition
           ^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 112, in condition
    if self.coordinator.get_current(FIELD_CONDITIONS) in CONDITION_MAP:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/coordinator.py", line 156, in get_current
    result = self.get_from_dict(self.data[RESULTS_CURRENT], keys)
                                ~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by codyc1515** [comment]
The new `mobile-api` branch dropped in and worked for me with no issues.

**Comment by codyc1515** [comment]
Great. So, everything is working in the mobile-app branch - except the Forecast. I got the following error:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/metservice_weather/coordinator.py:219
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:57:40 (5 occurrences)
Last logged: 10:17:07

[546830180032] Error handling message: Unknown error (unknown_error) Cody Cooper from 103.216.189.25 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
[546728372160] Error handling message: Unknown error (unknown_error) Cody Cooper from 103.216.189.25 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/weather/websocket_api.py", line 102, in ws_subscribe_forecast
    await entity.async_update_listeners({forecast_type})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 1072, in async_update_listeners
    native_forecast_list: list[Forecast] | None = await getattr(
                                                  ^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 155, in async_forecast_daily
    return self.forecast_daily
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 211, in forecast_daily
    num_days = self.coordinator.get_forecast_daily("", 0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/coordinator.py", line 219, in get_forecast_daily
    all_days = self.data[RESULTS_FORECAST_DAILY]["layout"]["primary"]["slots"][
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'layout'
```

**Comment by codyc1515** [comment]
The specific piece of code is here: https://github.com/ciejer/metservice-weather/blob/7271cf16d9055e7565eb5c3ef4d9375fb133c2e6/custom_components/metservice_weather/coordinator.py#L219

**Comment by codyc1515** [comment]
This is completed. Raised a new [issue for the forecast not working](https://github.com/ciejer/metservice-weather/issues/21).

**Comment by ciejer** [comment]
@jaymunro for my testing I used the one from @codyc1515 's example - however the mobile api is explicitly "not public" so in my role as plugin maintainer suggest use only if you have permission to do so.

When I first built this in, the codebase was not appropriately handling the arbitrary changes in public api structure - it is much more resilient now but mobile may be useful if your location is better described with lat/long than it can be by a town/city name.

**Comment by jaymunro** [comment]
@codyc1515. Just a heads up, you should obfuscate that api key in your issue description. That strikes me as something that could be abused.

@ciejer, Chris that api key would surely just give you Cody's geolocation and his forecast, not yours?

**Comment by ciejer** [comment]
@jaymunro I believe its a static key thats baked into the ios app, but Cody will be able to clarify I'm sure. I can confirm it works for any location; my implementation requests the lat/long of your homeassistant configuration in the api url, and simply uses the key to authenticate.

**Comment by jaymunro** [comment]
Ah, so that's the lat,long in Settings > Zones for the home? So we're not tracking Cody 😂. That's good.
I'm wondering which iOS app the key is from, Met Service or HA and if that key is the same for everyone (if it's baked into an app) or it's individually baked in from the Apple App Store.
https://developer.apple.com/documentation/appstoreserverapi/creating_api_keys_to_use_with_the_app_store_server_api ?  
And would this be broken for people on Android?

**Comment by codyc1515** [comment]
It's a generic key in the MetService iOS app.

**Comment by jaymunro** [comment]
Ah, so does not need to be obfuscated, or even exposed to the user. I.e. it could be baked into the integration?

**Comment by ciejer** [comment]
Potentially, but as a risk-averse developer building against an API with
"usage restricted" at the top, I'm not keen to do so - and to be fair the
service is ad-funded.

From my perspective, it's supported if someone wants to use a key - whether
discovered or legitimately acquired from metservice :)

**Comment by clowgg** [comment]
So - where do I find this API key for the Mobile API? I can't see it anywhere in the Met Service iOS app.

**Comment by dhi20** [comment]
Fantastic to be able to get MetService forecast into HA. Has anyone had any luck obtaining the key?

**Comment by orange-artworks** [comment]
I’d be keen to try the mobile API key too.
Anyone? 
Hopefully I could then use lat/long instead of a city/town. I could then see if forecasts were more accurate for my location.

**Comment by khcnz** [comment]
> I’d be keen to try the mobile API key too. Anyone? Hopefully I could then use lat/long instead of a city/town. I could then see if forecasts were more accurate for my location.

Hint: https://www.telerik.com/fiddler can be your friend

**Comment by dhi20** [comment]
Thanks kcvnz, I found the key_share but this doesn't seem to work.

**Comment by khcnz** [comment]
That's not the right field, you want to look at the HTTP headers for a clearly named key..
