### ISSUE TITLE
Forecast does not work with Mobile API

### ISSUE THREAD

**Issue by codyc1515** [ciejer/metservice-weather#21]
### System Health details

.

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The specific piece of code is here: https://github.com/ciejer/metservice-weather/blob/7271cf16d9055e7565eb5c3ef4d9375fb133c2e6/custom_components/metservice_weather/coordinator.py#L219

### Reproduction steps

1. Use Mobile API
2. Check logs / entities
3. Forecast is not unavailable due to an error

### Debug logs

```text
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/metservice_weather/coordinator.py:219
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:57:40 (5 occurrences)
Last logged: 10:17:07

[546830180032] Error handling message: Unknown error (unknown_error) Cody Cooper from 103.216.189.25 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
[546728372160] Error handling message: Unknown error (unknown_error) Cody Cooper from 103.216.189.25 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/weather/websocket_api.py", line 102, in ws_subscribe_forecast
    await entity.async_update_listeners({forecast_type})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 1072, in async_update_listeners
    native_forecast_list: list[Forecast] | None = await getattr(
                                                  ^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 155, in async_forecast_daily
    return self.forecast_daily
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 211, in forecast_daily
    num_days = self.coordinator.get_forecast_daily("", 0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/coordinator.py", line 219, in get_forecast_daily
    all_days = self.data[RESULTS_FORECAST_DAILY]["layout"]["primary"]["slots"][
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'layout'
```
```


### Diagnostics dump

_No response_

**Comment by ciejer** [comment]
Thanks for your legendary work @codyc1515!
v0.3.0 resolves this, including shipping your contributions; note you'll need to recreate the device in 'integrations' as this fix changes what is saved by the initial config flow.
