### ISSUE TITLE
All entities reporting "Unknown" State

### ISSUE THREAD

**Issue by BambamNZ** [ciejer/metservice-weather#84]
## System Information

version | core-2024.11.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.0-27-amd64
arch | x86_64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1460
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 4
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 16, 2024 at 2:56 AM
-- | --
current_recorder_run | November 23, 2024 at 4:05 PM
estimated_db_size | 92.04 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ciejer/metservice_weather/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

All entities related to Metservice Integration in and "Unknown" state 

### Reproduction steps

1. Load Integration is watch for error in logs 
2.
3.
...

### Debug logs

```text
First Error message: 

This error originated from a custom integration.

Logger: custom_components.metservice_weather.coordinator
Source: custom_components/metservice_weather/coordinator.py:322
integration: MetService New Zealand Weather (documentation, issues)
First occurred: November 23, 2024 at 4:05:27 PM (240 occurrences)
Last logged: 6:07:35 PM

Error retrieving public sensor 'hourly_bkp_obs': 'hourly_bkp_obs'
Error retrieving public sensor 'hourly_bkp_skip': 'hourly_bkp_skip'
Error retrieving public sensor 'hourly_bkp_temp': 'hourly_bkp_temp'

Second Error message:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/metservice_weather/weather.py:373
integration: MetService New Zealand Weather (documentation, issues)
First occurred: November 23, 2024 at 4:25:27 PM (78 occurrences)
Last logged: 6:07:35 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 1216, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 561, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 339, in extra_state_attributes
    'forecast_hourly': self.forecast_hourly,
                       ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 373, in forecast_hourly
    hourly_obs + hourly_skip,
    ~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

### Diagnostics dump

[home-assistant_metservice_weather_2024-11-24T05-26-27.286Z.log](https://github.com/user-attachments/files/17892098/home-assistant_metservice_weather_2024-11-24T05-26-27.286Z.log)

**Comment by ratkinsoncinz** [comment]
Adding my error, the same one as above so probably not _super_ helpful, but whatever.

I am running HA Supervised on x86, same build.

`Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:599
integration: Weather (documentation, issues)
First occurred: 3:05:42 PM (2 occurrences)
Last logged: 3:53:46 PM

Error adding entity weather.home for domain weather with platform metservice_weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 339, in extra_state_attributes
    'forecast_hourly': self.forecast_hourly,
                       ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 373, in forecast_hourly
    hourly_obs + hourly_skip,
    ~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'`

**Comment by davidjroos** [comment]
I'm getting complete breakage also, but slightly different issue?

```
Metservice Auckland Public
[21 entities](https://[mysite]/config/entities?historyBack=1&config_entry=01J4RD73J2YR71H782J0HQAKRD)
Failed setup, will retry: Data validation error: unexpected character: line 1 column 1 (char 0)`
```

and in a bit more detail
```
Logger: custom_components.metservice_weather.coordinator
Source: custom_components/metservice_weather/coordinator.py:238
integration: MetService New Zealand Weather ([documentation](https://github.com/ciejer/metservice-weather), [issues](https://github.com/ciejer/metservice-weather/issues))
First occurred: 07:49:36 (21 occurrences)
Last logged: 07:57:45
Data validation error: unexpected character: line 1 column 1 (char 0)
```

**Comment by jabbajohnson** [comment]
It have a similar issue, went down the uninstall and reinstate path and now cannot reinstall I get an "unknown error" message come back after submitting any town/city with the public API option, both with tide info option selected and not... hope this helps!

**Comment by beejay31** [comment]
I have similar issues too since updating to 0.70.0 with Core 2024.11.3 here's my debug log:

2024-11-26 18:57:19.008 DEBUG (MainThread) [custom_components.metservice_weather.coordinator] Finished fetching WeatherUpdateCoordinator data in 0.417 seconds (success: True)
2024-11-26 18:57:19.015 ERROR (MainThread) [custom_components.metservice_weather.coordinator] Error retrieving public sensor 'hourly_bkp_obs': 'hourly_bkp_obs'
2024-11-26 18:57:19.015 ERROR (MainThread) [custom_components.metservice_weather.coordinator] Error retrieving public sensor 'hourly_bkp_skip': 'hourly_bkp_skip'
2024-11-26 18:57:19.015 ERROR (MainThread) [custom_components.metservice_weather.coordinator] Error retrieving public sensor 'hourly_bkp_temp': 'hourly_bkp_temp'
2024-11-26 18:57:19.016 ERROR (MainThread) [homeassistant.components.weather] Error adding entity weather.home for domain weather with platform metservice_weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 918, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 339, in extra_state_attributes
    'forecast_hourly': self.forecast_hourly,
                       ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/metservice_weather/weather.py", line 373, in forecast_hourly
    hourly_obs + hourly_skip,
    ~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
2024-11-26 18:57:19.027 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Forecast Description Updated Time' has no data.
2024-11-26 18:57:19.027 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Forecast Description Updated Time' has no attributes data.
2024-11-26 18:57:19.028 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Weather Description' has no data.
2024-11-26 18:57:19.028 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Weather Description' has no attributes data.
2024-11-26 18:57:19.028 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Relative Humidity' has no data.
2024-11-26 18:57:19.028 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Relative Humidity' has no attributes data.
2024-11-26 18:57:19.029 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'UV Index' has no data.
2024-11-26 18:57:19.029 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'UV Index' has no attributes data.
2024-11-26 18:57:19.029 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Wind Direction' has no data.
2024-11-26 18:57:19.029 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Wind Direction' has no attributes data.
2024-11-26 18:57:19.029 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Temperature - Feels Like' has no data.
2024-11-26 18:57:19.029 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Temperature - Feels Like' has no attributes data.
2024-11-26 18:57:19.029 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Temperature' has no data.
2024-11-26 18:57:19.029 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Temperature' has no attributes data.
2024-11-26 18:57:19.030 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Pressure' has no data.
2024-11-26 18:57:19.030 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Pressure' has no attributes data.
2024-11-26 18:57:19.030 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Wind Gust' has no data.
2024-11-26 18:57:19.030 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Wind Gust' has no attributes data.
2024-11-26 18:57:19.030 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Wind Speed' has no data.
2024-11-26 18:57:19.030 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Wind Speed' has no attributes data.
2024-11-26 18:57:19.030 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Pressure Tendency Trend' has no data.
2024-11-26 18:57:19.030 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Pressure Tendency Trend' has no attributes data.
2024-11-26 18:57:19.031 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Pollen Levels' has no data.
2024-11-26 18:57:19.031 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Pollen Levels' has no attributes data.
2024-11-26 18:57:19.031 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Pollen Type' has no data.
2024-11-26 18:57:19.031 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Pollen Type' has no attributes data.
2024-11-26 18:57:19.031 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'MetService Weather Warnings' has no data.
2024-11-26 18:57:19.031 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'MetService Weather Warnings' has no attributes data.
2024-11-26 18:57:19.031 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Fire Season' has no data.
2024-11-26 18:57:19.031 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Fire Season' has no attributes data.
2024-11-26 18:57:19.032 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Fire Danger' has no data.
2024-11-26 18:57:19.032 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Fire Danger' has no attributes data.
2024-11-26 18:57:19.032 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Clothes Drying Time - Morning' has no data.
2024-11-26 18:57:19.032 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Clothes Drying Time - Morning' has no attributes data.
2024-11-26 18:57:19.032 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Clothes Drying Time - Afternoon' has no data.
2024-11-26 18:57:19.032 DEBUG (MainThread) [custom_components.metservice_weather.sensor] Sensor 'Clothes Drying Time - Afternoon' has no attributes data.
2024-11-26 18:57:20.734 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (as_timestamp(states('sensor.home_forecast_description_updated_time')) + 0) | timestamp_custom('%B %-d %-I:%M %p') }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2117, in forgiving_as_timestamp
    return dt_util.as_timestamp(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 153, in as_timestamp
    raise ValueError("not a valid date/time.")
ValueError: not a valid date/time.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2735, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2120, in forgiving_as_timestamp
    raise_no_default("as_timestamp", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1911, in raise_no_default
    raise ValueError(
ValueError: Template error: as_timestamp got invalid input 'unknown' when rendering template '{{ (as_timestamp(states('sensor.home_forecast_description_updated_time')) + 0) | timestamp_custom('%B %-d %-I:%M %p') }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 750, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 635, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: as_timestamp got invalid input 'unknown' when rendering template '{{ (as_timestamp(states('sensor.home_forecast_description_updated_time')) + 0) | timestamp_custom('%B %-d %-I:%M %p') }}' but no default was specified
2024-11-26 18:57:20.736 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: as_timestamp got invalid input 'unknown' when rendering template '{{ (as_timestamp(states('sensor.home_forecast_description_updated_time')) + 0) | timestamp_custom('%B %-d %-I:%M %p') }}' but no default was specified') while processing template 'Template<template=({{ (as_timestamp(states('sensor.home_forecast_description_updated_time')) + 0) | timestamp_custom('%B %-d %-I:%M %p') }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.home_weather_last_updated'

**Comment by mavnz72** [comment]
> I have a similar issue, went down the uninstall and reinstate path and now cannot reinstall I get an "unknown error" message come back after submitting any town/city with the public API option, both with tide info option selected and not... hope this helps!

The URLs in const.py seem to be incorrect.   Napier was missing /regions/hawkes-bay.  Without the correct URL, your unknown error is a 404 in the log file.
    {"label": "Hastings", "value": "/towns-cities/locations/hastings"},
    {"label": "Mahia", "value": "/rural/regions/hawkes-bay/locations/mahia"},
    {"label": "Napier", "value": "/towns-cities/regions/hawkes-bay/locations/napier"},

**Comment by ciejer** [comment]
Hi all,
v0.8.0 _should_ fix it - found an ugly but simple solution.
If it doesn't work after HACS update and restart, try deleting and recreating your integration entry.

**Comment by beejay31** [comment]
Can confirm a redownload of v0.8.0 and a restart has fixed and all entities now have weather data,  thankyou very much for fixing :)

**Comment by mavnz72** [comment]
Thanks for the fast fix.  Update and restart worked fine.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
